version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./confs/nginx_1.conf:/etc/nginx/nginx.conf
      - ./static_files:/var/www/html

  backend:
    build:
      context: ./backend
    command: "uwsgi --wsgi-file wsgi.py --http :9000"